services:
    db:
        image: postgres:15
        container_name: project_db
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - project_data:/var/lib/postgresql/data

volumes:
    project_data: